/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness only. Reveals nothing about configuration, data, or version.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Overview
         * @description Everything the Overview screen shows, for the authenticated owner.
         *
         *     The owner is the session row's. Nothing in the query, the headers, or the
         *     body can name a different account.
         */
        get: operations["get_overview_v1_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whoami
         * @description Echo the authenticated owner.
         *
         *     Exists to prove both locks end to end. The value returned is the one the
         *     session row resolved to, never anything the caller supplied.
         */
        get: operations["whoami_v1_session_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trades List
         * @description The Trades list for the authenticated owner.
         *
         *     The owner is the session row's, never the query. `limit`/`offset` are
         *     clamped inside `list_trades` itself, so a caller requesting `limit=1000`
         *     gets 100 back rather than a 422 — the service is the one source of truth
         *     for the bound, matching `list_trades`'s own contract.
         */
        get: operations["get_trades_list_v1_trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trades/{trade_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trade Detail
         * @description One trade, plus presigned URLs for its screenshots.
         *
         *     `get_trade` already filters on `Trade.user_id == owner`, so a trade
         *     belonging to another account is indistinguishable from a nonexistent one
         *     at the ORM layer — this handler preserves that by raising the identical
         *     404 either way, never a 403.
         */
        get: operations["get_trade_detail_v1_trades__trade_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Trade Endpoint
         * @description Delete one trade, its screenshot rows, and its stored images.
         *
         *     **Objects go before the row, and only a complete cleanup earns the row's
         *     removal.** `screenshots.trade_id` is `ondelete="CASCADE"`, so dropping the
         *     trade drops the screenshot ROW while leaving the R2 OBJECT behind — and
         *     the row was the only record of that object's key. Deleting the row first,
         *     or deleting it anyway after a failed cleanup, would strand private images
         *     in the bucket with nothing left pointing at them.
         *
         *     So an INCOMPLETE cleanup returns 503 with the row intact — incomplete
         *     meaning anything left behind, whether it failed or was skipped as a key
         *     this owner may not delete. That is deliberately the less tidy outcome:
         *     telling a trader their screenshots are gone while they remain in the
         *     bucket is a false privacy assurance, and a blocked delete is recoverable
         *     where a silent orphan is not.
         */
        delete: operations["delete_trade_endpoint_v1_trades__trade_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Trade
         * @description Edit the user-editable fields of one trade.
         *
         *     The body is a positive allowlist (`schemas.trades.TradeUpdate`), so
         *     ownership and server-owned metadata are unreachable no matter what is
         *     sent. `exclude_unset=True` is what separates "leave this alone" from
         *     "clear this": both are legitimate intentions and both are expressible.
         *
         *     `expected_updated_at` is enforced inside a single conditional UPDATE in
         *     the service — see `update_trade_if_unchanged`. A stale value returns 409
         *     carrying the current timestamp so the client can show what changed rather
         *     than silently discarding the trader's typing.
         */
        patch: operations["patch_trade_v1_trades__trade_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BreakdownRow */
        BreakdownRow: {
            /** Label */
            label: string;
            /** Net Pnl */
            net_pnl: number;
            /** Trades */
            trades: number;
        };
        /** Calendar */
        Calendar: {
            /** Days */
            days: components["schemas"]["CalendarDay"][];
            /** Month */
            month: number;
            /** Year */
            year: number;
        };
        /** CalendarDay */
        CalendarDay: {
            /** Date */
            date: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "positive" | "negative" | "flat" | "unknown";
            /** Pnl */
            pnl: number | null;
        };
        /** EdgeLeak */
        EdgeLeak: {
            amount: components["schemas"]["Undefinable"];
            /** Recorded */
            recorded: number;
            /** Trades */
            trades: number;
        };
        /** EquityPoint */
        EquityPoint: {
            /** Date */
            date: string;
            /** Equity */
            equity: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Kpi */
        Kpi: {
            /** Expectancy */
            expectancy: number | null;
            /** Expectancy State */
            expectancy_state: ("undefined_nan" | "undefined_positive_infinity" | "undefined_negative_infinity" | "undefined_no_sample" | "undefined_incomplete_sample") | null;
            /** Losses */
            losses: number;
            net_pnl: components["schemas"]["Undefinable"];
            /** Profit Factor */
            profit_factor: number | null;
            /** Profit Factor State */
            profit_factor_state: ("undefined_nan" | "undefined_positive_infinity" | "undefined_negative_infinity" | "undefined_no_sample" | "undefined_incomplete_sample") | null;
            today_pnl: components["schemas"]["Undefinable"];
            /** Trades */
            trades: number;
            week_pnl: components["schemas"]["Undefinable"];
            win_rate: components["schemas"]["Undefinable"];
            /** Wins */
            wins: number;
        };
        /**
         * NextReviewAction
         * @description The trader's position on the activation path.
         *
         *     `next_key` is a closed set rather than a free string, so the generated
         *     TypeScript is a union the client can key its copy off exhaustively. It was
         *     a bare `str`, and the web card was written against three invented spellings
         *     — two of which no service ever emits, so the card fell through to "the
         *     activation path is complete" while it displayed "1 of 3 done". A union
         *     makes that a compile error instead of a contradiction on screen.
         *     `tests/test_activation.py` pins these members to `activation.STEP_KEYS`.
         */
        NextReviewAction: {
            /** Completed */
            completed: number;
            /** Is Activated */
            is_activated: boolean;
            /** Next Key */
            next_key: ("strategy" | "first_trade" | "weekly_review") | null;
            /** Total */
            total: number;
            /** Trades Until Review */
            trades_until_review: number;
        };
        /** OverviewResponse */
        OverviewResponse: {
            calendar: components["schemas"]["Calendar"];
            kpi: components["schemas"]["Kpi"];
            next_review_action: components["schemas"]["NextReviewAction"];
            period: components["schemas"]["Period"];
            /** Recent Trades */
            recent_trades: components["schemas"]["RecentTrade"][];
            recurring_edge: components["schemas"]["RecurringEdge"];
            risk: components["schemas"]["Risk"];
            sample: components["schemas"]["SampleFlags"];
            trajectory: components["schemas"]["Trajectory"];
        };
        /** Period */
        Period: {
            /** From */
            from: string;
            /** To */
            to: string;
        };
        /** RecentTrade */
        RecentTrade: {
            /** Asset */
            asset: string | null;
            /** Id */
            id: number;
            /** Pnl */
            pnl: number | null;
            /** Result */
            result: ("Win" | "Loss" | "Breakeven") | null;
            /** Rr Realized */
            rr_realized: number | null;
            /** Session */
            session: string | null;
            /** Setup Type */
            setup_type: string | null;
            /** Trade Date */
            trade_date: string | null;
        };
        /** RecurringEdge */
        RecurringEdge: {
            /** Killzones */
            killzones: components["schemas"]["BreakdownRow"][];
            /** Setups */
            setups: components["schemas"]["BreakdownRow"][];
        };
        /** Risk */
        Risk: {
            consistency: components["schemas"]["Undefinable"];
            edge_leak: components["schemas"]["EdgeLeak"];
            max_drawdown: components["schemas"]["Undefinable"];
            rule_adherence: components["schemas"]["RuleAdherence"];
        };
        /** RuleAdherence */
        RuleAdherence: {
            /** Followed */
            followed: number;
            /** Rate */
            rate: number | null;
            /** Recorded */
            recorded: number;
        };
        /** SampleFlags */
        SampleFlags: {
            /** Dated Points */
            dated_points: number;
            /** Pnl Complete */
            pnl_complete: boolean;
            /** Pnl Recorded */
            pnl_recorded: number;
            /** Show Comparisons */
            show_comparisons: boolean;
            /** Show Dominant Series */
            show_dominant_series: boolean;
            /** Show Patterns */
            show_patterns: boolean;
            /** Show Series */
            show_series: boolean;
            /** Show Summary */
            show_summary: boolean;
            /** Trades */
            trades: number;
        };
        /**
         * ScreenshotCleanupFailedDetail
         * @description A delete that could not finish. The trade row is deliberately still
         *     there: a trader told their screenshots are gone while private images
         *     remain in the bucket has been given a false privacy assurance, so the
         *     state stays retryable rather than becoming an orphan nobody can find.
         *
         *     `remaining` and `unresolvable` are separate numbers because they need
         *     different handling: `remaining` is an object-store fault that a retry
         *     will clear, while `unresolvable` counts screenshot rows naming a path
         *     this owner is not entitled to delete — a retry will never clear those,
         *     and the caller must be able to tell "try again" from "this needs an
         *     operator" rather than seeing one opaque total.
         */
        ScreenshotCleanupFailedDetail: {
            /**
             * Error
             * @constant
             */
            error: "screenshot_cleanup_failed";
            /** Remaining */
            remaining: number;
            /** Unresolvable */
            unresolvable: number;
        };
        /** ScreenshotCleanupFailedResponse */
        ScreenshotCleanupFailedResponse: {
            detail: components["schemas"]["ScreenshotCleanupFailedDetail"];
        };
        /**
         * ScreenshotDescriptor
         * @description A screenshot with a short-lived presigned download URL.
         *
         *     `url` is `None` when `presign_download` returned `None` for this object
         *     (rare — `finalize_upload` only ever stores a resolvable key) rather than
         *     surfacing an error; the caller simply has no image to render for that
         *     entry.
         */
        ScreenshotDescriptor: {
            /** Height */
            height: number | null;
            /** Id */
            id: number;
            /** Uploaded At */
            uploaded_at: string | null;
            /** Url */
            url: string | null;
            /** Width */
            width: number | null;
        };
        /**
         * TradeConflictDetail
         * @description What the client needs to show a trader whose edit lost a race.
         */
        TradeConflictDetail: {
            /** Current Updated At */
            current_updated_at: string | null;
            /**
             * Error
             * @constant
             */
            error: "stale_trade";
        };
        /**
         * TradeConflictResponse
         * @description The 409 body. Shaped to match FastAPI's `{"detail": ...}` envelope so
         *     the generated TypeScript describes what actually arrives.
         */
        TradeConflictResponse: {
            detail: components["schemas"]["TradeConflictDetail"];
        };
        /**
         * TradeDetail
         * @description The full trade record plus its screenshots.
         *
         *     Server-owned and internal fields (`user_id`, `trade_hash`, `is_sample`,
         *     `strategy_id`) are deliberately absent — this is a read contract, not the
         *     ORM's column set, and none of those are anything a client should see or
         *     ever be able to round-trip back through a future PATCH.
         */
        TradeDetail: {
            /** Ai Grade */
            ai_grade: string | null;
            /** Asset */
            asset: string | null;
            /** Asset Class */
            asset_class: string | null;
            /** Bias */
            bias: string | null;
            /** Bos */
            bos: number | null;
            /** Choch */
            choch: number | null;
            /** Confirmation Model */
            confirmation_model: string | null;
            /** Created At */
            created_at: string | null;
            /** Day Of Week */
            day_of_week: string | null;
            /** Direction */
            direction: string | null;
            /** Emotions After */
            emotions_after: string | null;
            /** Emotions Before */
            emotions_before: string | null;
            /** Emotions During */
            emotions_during: string | null;
            /** Entry Price */
            entry_price: number | null;
            /** Entry Type */
            entry_type: string | null;
            /** Exit Price */
            exit_price: number | null;
            /** Followed Rules */
            followed_rules: number | null;
            /** Fvg Used */
            fvg_used: number | null;
            /** Htf Bias */
            htf_bias: string | null;
            /** Id */
            id: number;
            /** Killzone */
            killzone: string | null;
            /** Liquidity Sweep */
            liquidity_sweep: number | null;
            /** Mistake Tags */
            mistake_tags: string | null;
            /** Notes */
            notes: string | null;
            /** Order Block Used */
            order_block_used: number | null;
            /** Pnl */
            pnl: number | null;
            /** Position Size */
            position_size: number | null;
            /** Result */
            result: ("Win" | "Loss" | "Breakeven") | null;
            /** Reward Amount */
            reward_amount: number | null;
            /** Risk Amount */
            risk_amount: number | null;
            /** Rr Planned */
            rr_planned: number | null;
            /** Rr Realized */
            rr_realized: number | null;
            /** Screenshots */
            screenshots: components["schemas"]["ScreenshotDescriptor"][];
            /** Session */
            session: string | null;
            /** Setup Type */
            setup_type: string | null;
            /** Stop Price */
            stop_price: number | null;
            /** Strategy Used */
            strategy_used: string | null;
            /** Timeframe */
            timeframe: string | null;
            /** Tp Price */
            tp_price: number | null;
            /** Trade Date */
            trade_date: string | null;
            /** Trade Process Notes */
            trade_process_notes: string | null;
            /** Updated At */
            updated_at: string | null;
            /** User Grade */
            user_grade: string | null;
        };
        /** TradeListResponse */
        TradeListResponse: {
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
            /** Trades */
            trades: components["schemas"]["TradeSummary"][];
        };
        /**
         * TradeSummary
         * @description One row of the Trades list — deliberately narrower than TradeDetail.
         *
         *     The list view does not need every SMC/ICT annotation field; Trade Detail
         *     (below) is where the full record lives.
         */
        TradeSummary: {
            /** Ai Grade */
            ai_grade: string | null;
            /** Asset */
            asset: string | null;
            /** Direction */
            direction: string | null;
            /** Id */
            id: number;
            /** Killzone */
            killzone: string | null;
            /** Pnl */
            pnl: number | null;
            /** Result */
            result: ("Win" | "Loss" | "Breakeven") | null;
            /** Rr Realized */
            rr_realized: number | null;
            /** Screenshot Count */
            screenshot_count: number;
            /** Session */
            session: string | null;
            /** Setup Type */
            setup_type: string | null;
            /** Trade Date */
            trade_date: string | null;
            /** User Grade */
            user_grade: string | null;
        };
        /**
         * TradeUpdate
         * @description The PATCH body — a POSITIVE allowlist of genuinely user-editable fields.
         *
         *     `trade_service.update_trade` accepts every column except `id` and
         *     `user_id`. That is right for a trusted in-process caller and wrong at an
         *     HTTP edge, so this model names the editable fields and nothing else;
         *     `extra="forbid"` refuses the rest. Ownership and server-owned metadata —
         *     `user_id`, `id`, `trade_hash`, `is_sample`, `created_at`, `updated_at`,
         *     `strategy_id` — are therefore unreachable through HTTP input whatever the
         *     request says.
         *
         *     Because the allowlist is positive, a new column on the `Trade` model is
         *     NOT editable until someone deliberately adds it here. The safe default
         *     survives schema growth, and `SERVER_OWNED_TRADE_COLUMNS` below makes that
         *     growth visible: a column in neither set fails the contract test.
         *
         *     Every field defaults to unset, and the handler dumps with
         *     `exclude_unset=True`, so an omitted field is left alone while an explicit
         *     `null` clears the column. Those two are different intentions and the wire
         *     format can express both.
         *
         *     `expected_updated_at` is required, not optional. Inline editing on a page
         *     a trader may have left open invites the lost-update problem, and a guard
         *     a client can skip by omitting a field is not a guard.
         */
        TradeUpdate: {
            /** Asset */
            asset?: string | null;
            /** Direction */
            direction?: string | null;
            /** Expected Updated At */
            expected_updated_at: string;
            /** Followed Rules */
            followed_rules?: number | null;
            /** Htf Bias */
            htf_bias?: string | null;
            /** Killzone */
            killzone?: string | null;
            /** Mistake Tags */
            mistake_tags?: string | null;
            /** Notes */
            notes?: string | null;
            /** Pnl */
            pnl?: number | null;
            /** Result */
            result?: ("Win" | "Loss" | "Breakeven") | null;
            /** Risk Amount */
            risk_amount?: number | null;
            /** Rr Realized */
            rr_realized?: number | null;
            /** Session */
            session?: string | null;
            /** Setup Type */
            setup_type?: string | null;
            /** Timeframe */
            timeframe?: string | null;
            /** Trade Date */
            trade_date?: string | null;
        };
        /** Trajectory */
        Trajectory: {
            average_loss: components["schemas"]["Undefinable"];
            average_win: components["schemas"]["Undefinable"];
            /** Best Streak */
            best_streak: number;
            /** Current Streak */
            current_streak: number;
            /** Equity Curve */
            equity_curve: components["schemas"]["EquityPoint"][];
            /**
             * Streak Type
             * @enum {string}
             */
            streak_type: "win" | "loss" | "none";
            /** Worst Streak */
            worst_streak: number;
        };
        /**
         * Undefinable
         * @description A possibly-undefined number as {value, state}.
         *
         *     Both fields are required (no `= None` default) even though both are
         *     `Optional` in type: `_pair`/`_sample_pair` on the service side always emit
         *     both keys together, so a payload with one missing is a shape change to
         *     catch here, not a plain absence to paper over with a default null.
         */
        Undefinable: {
            /** State */
            state: ("undefined_nan" | "undefined_positive_infinity" | "undefined_negative_infinity" | "undefined_no_sample" | "undefined_incomplete_sample") | null;
            /** Value */
            value: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WhoAmI */
        WhoAmI: {
            /** User Id */
            user_id: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_overview_v1_overview_get: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whoami_v1_session_whoami_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoAmI"];
                };
            };
        };
    };
    get_trades_list_v1_trades_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                asset?: string | null;
                session?: string | null;
                setup?: string | null;
                result?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trade_detail_v1_trades__trade_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trade_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_trade_endpoint_v1_trades__trade_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trade_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenshotCleanupFailedResponse"];
                };
            };
        };
    };
    patch_trade_v1_trades__trade_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trade_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeConflictResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
