"""add full trade schema

Revision ID: 8383cf3ef6e7
Revises: 81413d7231da
Create Date: 2026-05-30 16:56:28.212257

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8383cf3ef6e7"
down_revision: Union[str, Sequence[str], None] = "81413d7231da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # screenshots columns (width/height/uploaded_at) were added outside migrations — skip
    op.add_column("trades", sa.Column("trade_date", sa.String(), nullable=True))
    op.add_column("trades", sa.Column("day_of_week", sa.String(), nullable=True))
    op.add_column("trades", sa.Column("session", sa.String(), nullable=True))
    op.add_column("trades", sa.Column("asset_class", sa.String(), nullable=True))
    op.add_column("trades", sa.Column("bias", sa.String(), nullable=True))
    op.add_column("trades", sa.Column("stop_price", sa.Float(), nullable=True))
    op.add_column("trades", sa.Column("tp_price", sa.Float(), nullable=True))
    op.add_column("trades", sa.Column("position_size", sa.Float(), nullable=True))
    op.add_column("trades", sa.Column("risk_amount", sa.Float(), nullable=True))
    op.add_column("trades", sa.Column("reward_amount", sa.Float(), nullable=True))
    op.add_column("trades", sa.Column("rr_planned", sa.Float(), nullable=True))
    op.add_column("trades", sa.Column("strategy_used", sa.String(), nullable=True))
    op.add_column("trades", sa.Column("emotions_during", sa.String(), nullable=True))
    op.add_column("trades", sa.Column("emotions_after", sa.String(), nullable=True))
    op.add_column("trades", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column("trades", sa.Column("ai_grade", sa.String(), nullable=True))
    op.add_column("trades", sa.Column("user_grade", sa.String(), nullable=True))
    op.add_column("trades", sa.Column("created_at", sa.String(), nullable=True))
    op.add_column("trades", sa.Column("updated_at", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trades", "updated_at")
    op.drop_column("trades", "created_at")
    op.drop_column("trades", "user_grade")
    op.drop_column("trades", "ai_grade")
    op.drop_column("trades", "notes")
    op.drop_column("trades", "emotions_after")
    op.drop_column("trades", "emotions_during")
    op.drop_column("trades", "strategy_used")
    op.drop_column("trades", "rr_planned")
    op.drop_column("trades", "reward_amount")
    op.drop_column("trades", "risk_amount")
    op.drop_column("trades", "position_size")
    op.drop_column("trades", "tp_price")
    op.drop_column("trades", "stop_price")
    op.drop_column("trades", "bias")
    op.drop_column("trades", "asset_class")
    op.drop_column("trades", "session")
    op.drop_column("trades", "day_of_week")
    op.drop_column("trades", "trade_date")
    # SQLite does not support ALTER CONSTRAINT — skip FK change
    op.drop_column("screenshots", "uploaded_at")
    op.drop_column("screenshots", "height")
    op.drop_column("screenshots", "width")
    # ### end Alembic commands ###
